quota: use iptables -j CLASSIFY, replaces tc + iptables

diff --git a/enable_quotas b/enable_quotas
--- a/enable_quotas
+++ b/enable_quotas
@@ -19,9 +19,9 @@ echo "for lan interface: $if_lan   range: [ $lan.$ip_start - $lan.$ip_end ]"
 echo "--------------------------------------------------------------------------------"
 echo ""
 
-indexes() { seq $ip_start $ip_end; }
-run() { echo "$@"; "$@"; r=$?; if [ $r != 0 ]; then echo "failed !"; fi; return $r;  }
-bit_set() {  [ $(( $1 & (1<<$2) )) != 0 ];  }
+indexes() {  seq $ip_start $ip_end;  }
+run()     {  echo "$@"; "$@"; r=$?; if [ $r != 0 ]; then echo "failed !"; fi; return $r;  }
+bit_set() {  [  $(( $1 & (1<<$2) )) != 0 ];  }
 
 
 #######################################################################
@@ -34,10 +34,9 @@ echo "resetting tc iptables and ipset"
 
 insmod sch_htb
 insmod sch_sfq
-insmod cls_fw
+# insmod cls_fw       # could remove now
 
 TCA="tc class add dev $if_lan"
-TFA="tc filter add dev $if_lan"
 TQA="tc qdisc add dev $if_lan"
 SFQ="sfq perturb 10"
 
@@ -48,66 +47,43 @@ for i in `indexes`; do
     # over quota speed limits
     $TCA parent 1: classid 1:$id htb rate ${dl_cap}kbit ceil ${dl_cap}kbit prio 2
     $TQA parent 1:$id handle $id: $SFQ
-    $TFA parent 1:0 prio 2 protocol ip handle $id fw flowid 1:$id
 
     id=$(($i + 512))
     # normal speed limits
     $TCA parent 1: classid 1:$id htb rate ${dl_cap_max}kbit ceil ${dl_cap_max}kbit prio 2
     $TQA parent 1:$id handle $id: $SFQ
-    $TFA parent 1:0 prio 2 protocol ip handle $id fw flowid 1:$id
 done
 
 #######################################################################
-# create ipsets
+# ipset
 
 insmod nfnetlink
 insmod ip_set
 insmod ip_set_bitmap_ip
 
-# ipset for accounting, no timeout
+# create ipset for accounting, no timeout
 run ipset create IP_QUOTA bitmap:ip range $lan.0/24 counters
 run ipset add IP_QUOTA $lan.$ip_start-$lan.$ip_end
 
-# lan ips bit sets
-for b in `seq 0 7`; do
-    echo "creating ipset IPS_BIT$b" 1>&2
-    echo "create IPS_BIT$b bitmap:ip range $lan.0/24"
-    for i in `indexes`; do
-	if bit_set $i $b; then
-	    echo "add IPS_BIT$b $lan.$i"
-	fi
-    done
-done | run ipset restore
-
 #######################################################################
-# iptables: check quotas and mark packets
+# iptables: check quotas and classify packets
 
 insmod xt_set
-
-# check quotas and set unique mark per ip (last digit).
-# ip bit sets allow to drastically reduce number of rules needed:
-# 8 rules instead of 256 to set a unique mark with naive (but simpler):
-#   for i in `indexes`; do
-#     iptables -j MARK --set-mark $i
-#   done
+insmod xt_CLASSIFY
 
 IPT="iptables -t mangle"
 IPT_POST="iptables -t mangle -A POSTROUTING -o $if_lan"
 
 run $IPT -N normal
 run $IPT -N overquota
-run $IPT_POST -j MARK --set-mark 0    # just be safe
-run $IPT_POST -m set --match-set IP_QUOTA dst --bytes-lt $dl_quota -j normal
-run $IPT_POST -m set --match-set IP_QUOTA dst --bytes-gt $dl_quota -j overquota
+run $IPT_POST -m set --match-set IP_QUOTA dst --bytes-gt $dl_quota -g overquota
+run $IPT_POST -m set --match-set IP_QUOTA dst ! --update-counters -g normal
 
-# set mark for regular download limit
-for b in `seq 0 7`; do		# set mark from ip lower bits
-    run $IPT -A normal -m set --match-set IPS_BIT$b dst -j MARK --or-mark $((1<<$b))
-done
-run $IPT -A normal -j MARK --or-mark 512
-
-# if over quota, set mark for hard speed limit
-for b in `seq 0 7`; do		# set mark from ip lower bits
-    run $IPT -A overquota -m set --match-set IPS_BIT$b dst -j MARK --or-mark $((1<<$b))
+# classify packets
+for i in `indexes`; do
+    echo "creating iptables rules for $lan.$i"
+    $IPT -A overquota --dst $lan.$i -j CLASSIFY --set-class 1:$i
+    $IPT -A normal    --dst $lan.$i -j CLASSIFY --set-class 1:$(($i + 512))
 done
 
+echo "done !"
