selfcontained: openwrt LEDE 17.01.4 update

diff --git a/selfcontained/get_files b/selfcontained/get_files
--- a/selfcontained/get_files
+++ b/selfcontained/get_files
@@ -1,7 +1,8 @@
 #!/bin/bash
 
 RELEASE="$1"
-ARCH="$2"
+TARGET="$2"
+ARCH="$3"
 
 die() {  echo "$@"; exit 1;  }
 get() {  [ -f "$1" ] && return 0; 
@@ -15,12 +16,31 @@ cd selfcontained
 rm -rf tmp packages data ../src_extra
 mkdir  tmp packages data 
 
-url="http://downloads.openwrt.org/$RELEASE/$ARCH/packages/base"
-get Packages "$url/Packages"
-./package_filenames < Packages > filenames
+base_url="http://downloads.openwrt.org/$RELEASE/packages/$ARCH/base"
+kmod_url="http://downloads.openwrt.org/$RELEASE/targets/$TARGET/packages"
+
+get_pkg_url()
+{
+    pkg="$1"
+
+    filename=`cat kmod_filenames | grep "^$pkg " | cut -d' ' -f2`
+    if [ -n "$filename" ]; then echo "$kmod_url/$filename"; return; fi
+
+    filename=`cat base_filenames | grep "^$pkg " | cut -d' ' -f2`
+    if [ -n "$filename" ]; then echo "$base_url/$filename"; return; fi
+
+    die "Couldn't find package '$f', this is bad."    
+}
+
+
+get Packages.1 "$base_url/Packages"
+./package_filenames < Packages.1 > base_filenames
+get Packages.2 "$kmod_url/Packages"
+./package_filenames < Packages.2 > kmod_filenames
+
 cat deps | while read f; do
-    filename=`cat filenames | grep "^$f " | cut -d' ' -f2`
-    get packages/$f.ipk "$url/$filename"
+    url=`get_pkg_url "$f"`
+    get packages/$f.ipk "$url"
     echo "extracting $f.ipk"
     cd tmp
     tar -xzf ../packages/$f.ipk
@@ -28,7 +48,7 @@ cat deps | while read f; do
     tar -xzf ../tmp/data.tar.gz
     cd ..
     rm tmp/*
-done
+done || exit 1
 
 cd data
 echo "packing needed files"
